Pro 5766 emulate mongo 3
apostrophecms/emulate-mongo-3-driver pull request #1
Opened 2024-04-04 09:58 UTC by haroun

## Summary

Emulate mongo 3 driver initial implementation

⚠️ I will detach the fork once this is approved, to avoid confusion when creating pull requests (one PR ended up in `emulate-mongo-2-driver` for some reason)

## What are the specific steps to test this change?

Please refer to https://github.com/apostrophecms/apostrophe/pull/4489

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-04-04 11:44 UTC, boutell requested changes
Makes sense to me, minor notes. Has this passed `npm test` of apostrophe core yet?

2024-04-04 11:44 UTC, boutell commented on README.md
>  `emulate-mongo-2-driver` aims to be a highly compatible emulation of the 2.x version of the MongoDB Node.js driver, implemented as a wrapper for the 3.x driver.
Update this paragraph

2024-04-04 11:44 UTC, boutell commented on collection.js
> +  Object.defineProperty(
What does this do?

2024-04-04 11:44 UTC, boutell commented on utils.js
> +    promise.then(
TIL: `.then` can also handle the `catch` case

2024-04-04 12:37 UTC, haroun commented on utils.js
> +    promise.then(
According to [Promise.then](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#onrejected) documentation, `onRejected` is optional

> A function to asynchronously execute when this promise becomes rejected. Its return value becomes the fulfillment value of the promise returned by then(). The function is called with the following arguments:
>
>>    [reason](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#reason)
>>
>>        The value that the promise was rejected with.
>
>    If it is not a function, it is internally replaced with a thrower function ((x) => { throw x; }) which throws the rejection reason it received.

My implementation will not diverge from the one provided by default `(x) => { throw x; }`.

2024-04-04 12:42 UTC, boutell commented on utils.js
> +    promise.then(
Well but you did diverge, by invoking the callback with the error, but that is good and needs to happen.

2024-04-04 12:49 UTC, haroun commented on collection.js
> +  Object.defineProperty(
It allows functions returning a `collection` in `db.js` (for example `renameCollection`) to return instances of my emulate classes instead of the parent classes.

2024-04-04 16:53 UTC, haroun commented
@boutell I've converted the PR to draft because we still have modules using `removeOne` and the cypress tests were red.

2024-04-05 16:06 UTC, haroun commented
@boutell I've updated the tests and my last cypress run was green.

2024-04-11 14:20 UTC, boutell approved these changes

2024-04-16 07:46 UTC, merged